export const data = {
  data: {
    metrics: [
      {
        timestamp: '2024-09-27T06:10:17.244973074Z',
        nodes: [
          {
            node_id: 'equus-feed-stag',
            type: 'SERVICE',
            calls: 5,
            successes: 0,
            failures: 0,
            latency_avg_ms: 7.0,
          },
          {
            node_id: 'mysql-service',
            type: 'DATABASE',
            calls: 61,
            successes: 61,
            failures: 0,
            latency_avg_ms: 2.081967213114754,
          },
          {
            node_id: 'equus-feed-prod',
            type: 'SERVICE',
            calls: 20,
            successes: 0,
            failures: 0,
            latency_avg_ms: 6.45,
          },
          {
            node_id: 'equus-api-gateway-stag',
            type: 'SERVICE',
            calls: 78,
            successes: 0,
            failures: 0,
            latency_avg_ms: 42.11538461538461,
          },
          {
            node_id: 'redis-service',
            type: 'DATABASE',
            calls: 140,
            successes: 140,
            failures: 0,
            latency_avg_ms: 6.957142857142857,
          },
          {
            node_id: 'equus-api-gateway-prod',
            type: 'SERVICE',
            calls: 57,
            successes: 0,
            failures: 0,
            latency_avg_ms: 596.1929824561404,
          },
          {
            node_id: 'equus-user-prod',
            type: 'SERVICE',
            calls: 40,
            successes: 0,
            failures: 0,
            latency_avg_ms: 477.1,
          },
          {
            node_id: 'equus-user-stag',
            type: 'SERVICE',
            calls: 53,
            successes: 0,
            failures: 0,
            latency_avg_ms: 14.88679245283019,
          },
          {
            node_id: 'equus-application-stag',
            type: 'SERVICE',
            calls: 51,
            successes: 0,
            failures: 0,
            latency_avg_ms: 26.470588235294116,
          },
          {
            node_id: 'equus-application-prod',
            type: 'SERVICE',
            calls: 6,
            successes: 0,
            failures: 0,
            latency_avg_ms: 59.833333333333336,
          },
          {
            node_id: 'equus-schedule-stag',
            type: 'SERVICE',
            calls: 42,
            successes: 0,
            failures: 0,
            latency_avg_ms: 3.2142857142857144,
          },
          {
            node_id: 'equus-schedule-prod',
            type: 'SERVICE',
            calls: 42,
            successes: 0,
            failures: 0,
            latency_avg_ms: 14.857142857142858,
          },
          {
            node_id: 'equus-status-stag',
            type: 'SERVICE',
            calls: 10,
            successes: 0,
            failures: 0,
            latency_avg_ms: 6.3,
          },
        ],
        edges: [
          {
            source: 'equus-api-gateway-stag',
            target: 'equus-feed-stag',
            interaction_type: 'HTTP',
            calls: 1,
            successes: 0,
            failures: 0,
            latency_avg_ms: 14.0,
          },
          {
            source: 'equus-feed-stag',
            target: 'mysql-service',
            interaction_type: 'DB',
            calls: 1,
            successes: 1,
            failures: 0,
            latency_avg_ms: 2.0,
          },
          {
            source: 'equus-api-gateway-stag',
            target: 'redis-service',
            interaction_type: 'DB',
            calls: 24,
            successes: 24,
            failures: 0,
            latency_avg_ms: 1.0,
          },
          {
            source: 'equus-api-gateway-prod',
            target: 'equus-feed-prod',
            interaction_type: 'HTTP',
            calls: 4,
            successes: 0,
            failures: 0,
            latency_avg_ms: 12.5,
          },
          {
            source: 'equus-feed-prod',
            target: 'mysql-service',
            interaction_type: 'DB',
            calls: 4,
            successes: 4,
            failures: 0,
            latency_avg_ms: 2.0,
          },
          {
            source: 'equus-api-gateway-stag',
            target: 'equus-application-stag',
            interaction_type: 'HTTP',
            calls: 10,
            successes: 0,
            failures: 0,
            latency_avg_ms: 60.7,
          },
          {
            source: 'equus-api-gateway-stag',
            target: 'equus-user-stag',
            interaction_type: 'HTTP',
            calls: 12,
            successes: 0,
            failures: 0,
            latency_avg_ms: 26.583333333333332,
          },
          {
            source: 'equus-api-gateway-stag',
            target: 'equus-schedule-stag',
            interaction_type: 'HTTP',
            calls: 3,
            successes: 0,
            failures: 0,
            latency_avg_ms: 14.666666666666666,
          },
          {
            source: 'equus-schedule-stag',
            target: 'mysql-service',
            interaction_type: 'DB',
            calls: 18,
            successes: 18,
            failures: 0,
            latency_avg_ms: 1.0555555555555556,
          },
          {
            source: 'equus-user-stag',
            target: 'redis-service',
            interaction_type: 'DB',
            calls: 62,
            successes: 62,
            failures: 0,
            latency_avg_ms: 1.1935483870967742,
          },
          {
            source: 'equus-user-stag',
            target: 'mysql-service',
            interaction_type: 'DB',
            calls: 5,
            successes: 5,
            failures: 0,
            latency_avg_ms: 1.6,
          },
          {
            source: 'equus-application-stag',
            target: 'mysql-service',
            interaction_type: 'DB',
            calls: 9,
            successes: 9,
            failures: 0,
            latency_avg_ms: 1.3333333333333333,
          },
          {
            source: 'equus-application-stag',
            target: 'equus-status-stag',
            interaction_type: 'HTTP',
            calls: 2,
            successes: 0,
            failures: 0,
            latency_avg_ms: 13.5,
          },
          {
            source: 'equus-status-stag',
            target: 'mysql-service',
            interaction_type: 'DB',
            calls: 2,
            successes: 2,
            failures: 0,
            latency_avg_ms: 1.0,
          },
          {
            source: 'equus-api-gateway-prod',
            target: 'equus-schedule-prod',
            interaction_type: 'HTTP',
            calls: 3,
            successes: 0,
            failures: 0,
            latency_avg_ms: 66.0,
          },
          {
            source: 'equus-schedule-prod',
            target: 'mysql-service',
            interaction_type: 'DB',
            calls: 18,
            successes: 18,
            failures: 0,
            latency_avg_ms: 3.111111111111111,
          },
          {
            source: 'equus-api-gateway-prod',
            target: 'redis-service',
            interaction_type: 'DB',
            calls: 12,
            successes: 12,
            failures: 0,
            latency_avg_ms: 6.25,
          },
          {
            source: 'equus-api-gateway-prod',
            target: 'equus-application-prod',
            interaction_type: 'HTTP',
            calls: 2,
            successes: 0,
            failures: 0,
            latency_avg_ms: 179.0,
          },
          {
            source: 'equus-api-gateway-prod',
            target: 'equus-user-prod',
            interaction_type: 'HTTP',
            calls: 10,
            successes: 0,
            failures: 0,
            latency_avg_ms: 738.1,
          },
          {
            source: 'equus-user-prod',
            target: 'redis-service',
            interaction_type: 'DB',
            calls: 37,
            successes: 37,
            failures: 0,
            latency_avg_ms: 10.054054054054054,
          },
          {
            source: 'equus-user-prod',
            target: 'mysql-service',
            interaction_type: 'DB',
            calls: 4,
            successes: 4,
            failures: 0,
            latency_avg_ms: 5.0,
          },
        ],
      },
    ],
  },
};
